### PR TITLE
Fix Issue #8 Endpoint Links Failing

### PR DESCRIPTION
**Pull request by bdeanindy**
- Fixed by escaping auto-URI generator indicated by scheme:// to scheme\://

@CHromek or @jasonrhodes could one of you review so I can merge this. I've added the labels for "Ready to Merge" so you can just update the label if it is good, thanks a bunch.

### CODE REVIEW

**Comment by jasonrhodes** [comment]
Hey @bdeanindy, I think this needs to go into SparkPost/sparkpost-api-documentation-DEV first? Also, what does it fix? Does it "de-linkify" those links?

**Comment by bdeanindy** [comment]
@jasonrhodes this is a hotfix and we can pull it into our internal DEV version. Yes this just "de-linkifies" the links. (love the technical terminology). :+1:

**Comment by CHromek** [comment]
This change looks ok to me. Just want to ensure that it gets back into the DEV version.

**Comment by bdeanindy** [comment]
Of course, it should be part of our deployment process from our DEV copy to pull from the master branch of this repository prior to pushing code (to resolve any conflicts and the like).

I'll merge this now into this repository.

Thanks @CHromek and @jasonrhodes :100:

**Pull request merged**
